---
linters:
  Comment:
    enabled: false
  Indentation:
    enabled: false
  StringQuotes:
    style: double_quotes
  PropertySortOrder:
    enabled: false
  FinalNewline:
    enabled: false
  LeadingZero:
    enabled: false